services:
  nginx:
    build: ./nginx
    networks:
      - inception-network
    ports:
      - 443:443
    restart: on-failure
  mariadb:
    build: ./mariadb
    networks:
      - inception-network
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
  wordpress:
    build: ./wordpress
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
networks:
  inception-network:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aakroud42/data/mariadb'

  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aakroud42/data/wordpress'




