server {
	listen 443 ssl;
	server_name aakroud.42.fr;

	ssl_certificate ./nginx-selfsigned.crt;
	ssl_certificate_key ./nginx-selfsigned.key;
	ssl_protocols TLSv1.3;

	root /var/www/wordpress;
	index index.php index.html;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}
}
